
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 19 15:26:34 CST 2018
//----------------------------------------------------

package Analizado_Lexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 2;
  public static final int LLAVI = 48;
  public static final int PARACADA = 19;
  public static final int LLAVF = 49;
  public static final int MULT = 30;
  public static final int CONJ = 36;
  public static final int ABRIR = 12;
  public static final int SI = 7;
  public static final int FUNCION = 6;
  public static final int RESTA = 29;
  public static final int DESDE = 13;
  public static final int ENTONCES = 9;
  public static final int CORCHETEFIN = 41;
  public static final int TNUMERO = 21;
  public static final int DECREMENTAR = 17;
  public static final int CORCHETEINI = 40;
  public static final int INCREMENTAR = 16;
  public static final int PRINCIPAL = 20;
  public static final int IGUAL = 38;
  public static final int SINO = 8;
  public static final int TAB = 51;
  public static final int MIENTRAS = 14;
  public static final int DIGUAL = 39;
  public static final int ESCRIBIR = 11;
  public static final int DIV = 31;
  public static final int PARFIN = 47;
  public static final int SUMA = 28;
  public static final int DISY = 35;
  public static final int ITERAR = 18;
  public static final int ID = 3;
  public static final int PARINI = 46;
  public static final int EOF = 0;
  public static final int CLASE = 5;
  public static final int error = 1;
  public static final int COMA = 44;
  public static final int NULO = 24;
  public static final int CADENA = 22;
  public static final int MODULO = 37;
  public static final int MENOR = 34;
  public static final int PCOMA = 43;
  public static final int EN = 27;
  public static final int MAYOR = 33;
  public static final int POTENCIA = 32;
  public static final int PUNTO = 45;
  public static final int INCLUIR = 4;
  public static final int FALSO = 26;
  public static final int DOSP = 42;
  public static final int HACER = 15;
  public static final int BOOLEANO = 23;
  public static final int RETORNAR = 10;
  public static final int VERDADERO = 25;
  public static final int TEXTO = 50;
}

